<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>atole_sim</name>
  <version>0.1.0</version>
  <description>Modo SIM: reproduce datasets como si fueran las cámaras.</description>
  <maintainer email="michellvsigno21@gmail.com">Michell IV</maintainer>
  <license>Proprietary</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>atole_interfaces</exec_depend>
  <exec_depend>atole_common</exec_depend>
  <exec_depend>std_srvs</exec_depend>

  <exec_depend>zed_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
